CREATE TABLE IF NOT EXISTS market_features_1m (
    id BIGSERIAL PRIMARY KEY,
    exchange TEXT NOT NULL,
    symbol TEXT NOT NULL,
    open_time TIMESTAMPTZ NOT NULL,
    candle_open NUMERIC(28, 12),
    candle_high NUMERIC(28, 12),
    candle_low NUMERIC(28, 12),
    candle_close NUMERIC(28, 12),
    candle_volume NUMERIC(28, 12),
    quote_count INTEGER NOT NULL DEFAULT 0,
    trade_count INTEGER NOT NULL DEFAULT 0,
    order_book_count INTEGER NOT NULL DEFAULT 0,
    mid_price_avg NUMERIC(28, 12),
    spread_avg NUMERIC(28, 12),
    spread_min NUMERIC(28, 12),
    spread_max NUMERIC(28, 12),
    spread_bps_avg NUMERIC(18, 8),
    trade_buy_count INTEGER NOT NULL DEFAULT 0,
    trade_sell_count INTEGER NOT NULL DEFAULT 0,
    buy_volume NUMERIC(28, 12) NOT NULL DEFAULT 0,
    sell_volume NUMERIC(28, 12) NOT NULL DEFAULT 0,
    trade_volume NUMERIC(28, 12) NOT NULL DEFAULT 0,
    trade_notional NUMERIC(28, 12) NOT NULL DEFAULT 0,
    trade_flow_imbalance NUMERIC(18, 8),
    orderbook_imbalance_avg NUMERIC(18, 8),
    orderbook_imbalance_min NUMERIC(18, 8),
    orderbook_imbalance_max NUMERIC(18, 8),
    bid_depth_top20_avg NUMERIC(28, 12),
    ask_depth_top20_avg NUMERIC(28, 12),
    volatility_1m NUMERIC(18, 8),
    quality_score NUMERIC(5, 2),
    is_tradeable_minute BOOLEAN NOT NULL DEFAULT false,
    quality_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (exchange, symbol, open_time)
);

CREATE INDEX IF NOT EXISTS idx_market_features_1m_symbol_time ON market_features_1m (symbol, open_time DESC);
